import type { Metadata } from "next";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-full">
      <Sidebar />
      <div className="flex-1">
        <Header />
        <main className="p-6 h-full  overflow-y-auto">
          {children}
        </main>
      </div>
    </div>
  );
}
