import type { Metadata } from "next";

import Header from "./components/Header";
import ProtectedRoute from "./components/ProtectedRoute";
import SidebarDesktop from "./components/SidebarDesktop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-full">
      <ProtectedRoute />
      <SidebarDesktop />
      <div className="flex-11">
        <Header />
        <main className="p-6 h-full  overflow-y-auto">{children}</main>
      </div>
    </div>
  );
}
